# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stream_digits',
                'doc_host': 'https://Iain-S.github.io',
                'git_url': 'https://github.com/Iain-S/stream_digits',
                'lib_path': 'stream_digits'},
  'syms': {'stream_digits.core': {'stream_digits.core.foo': ('core.html#foo', 'stream_digits/core.py')}}}
